# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Pre-commit hooks for general file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: mixed-line-ending

  # Python code formatting with Black
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=79"]

  # Python linting with flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=79", "--extend-ignore=E203,W503"]

  # Python type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
        args: ["--ignore-missing-imports", "--no-warn-return-any"]

  # Local hooks for project-specific commands
  - repo: local
    hooks:
      # Run tests before commit
      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        args: ["tests/", "-v", "--cov=unity_wrapper", "--cov-fail-under=50"]
        pass_filenames: false
        stages: [pre-commit]

      # Run make format to ensure code is formatted
      - id: make-format
        name: make format
        entry: make
        language: system
        args: ["format"]
        pass_filenames: false
        stages: [pre-commit]

      # Run make lint for comprehensive linting
      - id: make-lint
        name: make lint
        entry: make
        language: system
        args: ["lint"]
        pass_filenames: false
        stages: [pre-commit]

# Global configuration
fail_fast: false
default_stages: [pre-commit]

# Exclude certain files/directories
exclude: |
  (?x)^(
      .venv/|
      .git/|
      .pytest_cache/|
      __pycache__/|
      .coverage|
      htmlcov/|
      coverage.xml|
      build/|
      dist/|
      .*[.]egg-info/|
      packages/.*|
      .unity_wrapper_temp/|
      unity-tester/.*
  )$
