name: Unity Package Builder

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run daily at 02:00 UTC to check for updates
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Specific package to build (optional)'
        required: false
        type: string

env:
  PYTHON_VERSION: '3.13'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      packages-changed: ${{ steps.changes.outputs.packages }}
      config-changed: ${{ steps.changes.outputs.config }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            packages:
              - 'config/packages.yaml'
            config:
              - 'config/**'
              - 'src/**'
              - 'pyproject.toml'

  build-packages:
    needs: check-changes
    runs-on: ubuntu-latest
    if: needs.check-changes.outputs.packages-changed == 'true' || needs.check-changes.outputs.config-changed == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Check for package updates
        id: check-updates
        run: |
          echo "Checking for package updates..."
          unity-wrapper check > check_output.txt 2>&1
          cat check_output.txt
          
          # Check if any packages need updates
          if grep -q "Packages needing updates" check_output.txt; then
            echo "updates-needed=true" >> $GITHUB_OUTPUT
          else
            echo "updates-needed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Build specific package
        if: github.event.inputs.package_name != ''
        run: |
          echo "Building specific package: ${{ github.event.inputs.package_name }}"
          unity-wrapper build "${{ github.event.inputs.package_name }}"
          
      - name: Build all packages
        if: github.event.inputs.package_name == '' && steps.check-updates.outputs.updates-needed == 'true'
        run: |
          echo "Building all packages..."
          unity-wrapper build
          
      - name: Upload package artifacts
        if: steps.check-updates.outputs.updates-needed == 'true' || github.event.inputs.package_name != ''
        uses: actions/upload-artifact@v4
        with:
          name: unity-packages
          path: packages/
          retention-days: 30
          include-hidden-files: false
          
      - name: Publish packages to GitHub Package Registry
        if: (steps.check-updates.outputs.updates-needed == 'true' || github.event.inputs.package_name != '') && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Publishing packages to GitHub Package Registry..."
          unity-wrapper publish --token "$GITHUB_TOKEN"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          
      - name: Run tests
        run: |
          pytest --cov=unity_wrapper --cov-report=xml
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          
      - name: Run linting
        run: |
          black --check src tests
          flake8 src tests
          mypy src
